// 🌤️ YOUR OWN WEATHER DATA SYSTEM
// Completely your own weather data structure
// No dependency on any third-party API

export const YOUR_WEATHER_DATABASE = {
  'London': {
    id: 'city_001',
    name: 'London',
    country: 'United Kingdom',
    region: 'England',
    coordinates: {
      latitude: 51.5074,
      longitude: -0.1278,
      altitude: 11,
    },
    timezone: 'UTC',
    lastUpdated: '2026-09-14T09:28:29Z',

    current_conditions: {
      temperature: 15,
      temperature_feels_like: 13,
      condition: 'Overcast Clouds',
      condition_icon: '04d',
      condition_description: 'The sky is mostly covered with clouds',

      // Air data
      humidity: 72,
      pressure: 1013,
      pressure_trend: 'stable',
      dew_point: 10,

      // Visibility & UV
      visibility: 10000,
      uv_index: 3,

      // Wind
      wind: {
        speed: 4.5,
        direction: 'NW',
        direction_degrees: 315,
        gust: 7.2,
      },

      // Precipitation
      rain_1h: 0,
      snow_1h: 0,
      cloud_coverage: 85,
    },

    sunrise_sunset: {
      sunrise: 1694707200,
      sunset: 1694750400,
      day_length: 43200,
    },

    hourly_forecast: [
      {
        time: 1694707200,
        hour: '12:00',
        temperature: 15,
        humidity: 72,
        condition: 'Cloudy',
        condition_icon: '04d',
        wind_speed: 4.5,
        rain_probability: 10,
      },
      {
        time: 1694710800,
        hour: '13:00',
        temperature: 16,
        humidity: 68,
        condition: 'Cloudy',
        condition_icon: '04d',
        wind_speed: 4.2,
        rain_probability: 8,
      },
      {
        time: 1694714400,
        hour: '14:00',
        temperature: 17,
        humidity: 65,
        condition: 'Partly Cloudy',
        condition_icon: '03d',
        wind_speed: 3.8,
        rain_probability: 5,
      },
      {
        time: 1694718000,
        hour: '15:00',
        temperature: 18,
        humidity: 62,
        condition: 'Sunny',
        condition_icon: '02d',
        wind_speed: 3.5,
        rain_probability: 2,
      },
      {
        time: 1694721600,
        hour: '16:00',
        temperature: 17,
        humidity: 65,
        condition: 'Partly Cloudy',
        condition_icon: '03d',
        wind_speed: 4.0,
        rain_probability: 5,
      },
      {
        time: 1694725200,
        hour: '17:00',
        temperature: 16,
        humidity: 68,
        condition: 'Cloudy',
        condition_icon: '04d',
        wind_speed: 4.3,
        rain_probability: 10,
      },
      {
        time: 1694728800,
        hour: '18:00',
        temperature: 15,
        humidity: 70,
        condition: 'Cloudy',
        condition_icon: '04d',
        wind_speed: 4.6,
        rain_probability: 15,
      },
      {
        time: 1694732400,
        hour: '19:00',
        temperature: 14,
        humidity: 73,
        condition: 'Cloudy Night',
        condition_icon: '04n',
        wind_speed: 4.8,
        rain_probability: 20,
      },
    ],

    alerts: [],
    source: 'YourWeatherDB v1.0',
  },

  'New York': {
    id: 'city_002',
    name: 'New York',
    country: 'United States',
    region: 'New York',
    coordinates: {
      latitude: 40.7128,
      longitude: -74.006,
      altitude: 10,
    },
    timezone: 'America/New_York',
    lastUpdated: '2026-09-14T09:28:29Z',

    current_conditions: {
      temperature: 22,
      temperature_feels_like: 21,
      condition: 'Clear Sky',
      condition_icon: '01d',
      condition_description: 'Perfect sunny weather',
      humidity: 65,
      pressure: 1015,
      pressure_trend: 'rising',
      dew_point: 14,
      visibility: 10000,
      uv_index: 6,
      wind: {
        speed: 5.2,
        direction: 'S',
        direction_degrees: 180,
        gust: 8.5,
      },
      rain_1h: 0,
      snow_1h: 0,
      cloud_coverage: 5,
    },

    sunrise_sunset: {
      sunrise: 1694709600,
      sunset: 1694752800,
      day_length: 43200,
    },

    hourly_forecast: [
      {
        time: 1694709600,
        hour: '12:00',
        temperature: 22,
        humidity: 65,
        condition: 'Sunny',
        condition_icon: '01d',
        wind_speed: 5.2,
        rain_probability: 0,
      },
      {
        time: 1694713200,
        hour: '13:00',
        temperature: 23,
        humidity: 62,
        condition: 'Sunny',
        condition_icon: '01d',
        wind_speed: 4.9,
        rain_probability: 0,
      },
      {
        time: 1694716800,
        hour: '14:00',
        temperature: 24,
        humidity: 60,
        condition: 'Sunny',
        condition_icon: '01d',
        wind_speed: 4.6,
        rain_probability: 0,
      },
      {
        time: 1694720400,
        hour: '15:00',
        temperature: 25,
        humidity: 58,
        condition: 'Sunny',
        condition_icon: '01d',
        wind_speed: 4.3,
        rain_probability: 0,
      },
      {
        time: 1694724000,
        hour: '16:00',
        temperature: 24,
        humidity: 60,
        condition: 'Partly Cloudy',
        condition_icon: '02d',
        wind_speed: 4.7,
        rain_probability: 3,
      },
      {
        time: 1694727600,
        hour: '17:00',
        temperature: 23,
        humidity: 62,
        condition: 'Partly Cloudy',
        condition_icon: '02d',
        wind_speed: 5.0,
        rain_probability: 5,
      },
      {
        time: 1694731200,
        hour: '18:00',
        temperature: 22,
        humidity: 64,
        condition: 'Clear Night',
        condition_icon: '02n',
        wind_speed: 5.2,
        rain_probability: 5,
      },
      {
        time: 1694734800,
        hour: '19:00',
        temperature: 21,
        humidity: 66,
        condition: 'Clear Night',
        condition_icon: '01n',
        wind_speed: 5.3,
        rain_probability: 3,
      },
    ],

    alerts: [],
    source: 'YourWeatherDB v1.0',
  },

  'Tokyo': {
    id: 'city_003',
    name: 'Tokyo',
    country: 'Japan',
    region: 'Tokyo',
    coordinates: {
      latitude: 35.6762,
      longitude: 139.6503,
      altitude: 0,
    },
    timezone: 'Asia/Tokyo',
    lastUpdated: '2026-09-14T09:28:29Z',

    current_conditions: {
      temperature: 28,
      temperature_feels_like: 30,
      condition: 'Light Rain',
      condition_icon: '10d',
      condition_description: 'Light rain falling',
      humidity: 78,
      pressure: 1012,
      pressure_trend: 'falling',
      dew_point: 23,
      visibility: 8000,
      uv_index: 2,
      wind: {
        speed: 6.5,
        direction: 'E',
        direction_degrees: 90,
        gust: 11.2,
      },
      rain_1h: 2.5,
      snow_1h: 0,
      cloud_coverage: 95,
    },

    sunrise_sunset: {
      sunrise: 1694673600,
      sunset: 1694715600,
      day_length: 42000,
    },

    hourly_forecast: [
      {
        time: 1694673600,
        hour: '12:00',
        temperature: 28,
        humidity: 78,
        condition: 'Light Rain',
        condition_icon: '10d',
        wind_speed: 6.5,
        rain_probability: 80,
      },
      {
        time: 1694677200,
        hour: '13:00',
        temperature: 27,
        humidity: 80,
        condition: 'Light Rain',
        condition_icon: '10d',
        wind_speed: 6.8,
        rain_probability: 85,
      },
      {
        time: 1694680800,
        hour: '14:00',
        temperature: 26,
        humidity: 82,
        condition: 'Heavy Rain',
        condition_icon: '09d',
        wind_speed: 7.0,
        rain_probability: 90,
      },
      {
        time: 1694684400,
        hour: '15:00',
        temperature: 25,
        humidity: 80,
        condition: 'Heavy Rain',
        condition_icon: '09d',
        wind_speed: 6.5,
        rain_probability: 88,
      },
      {
        time: 1694688000,
        hour: '16:00',
        temperature: 26,
        humidity: 79,
        condition: 'Light Rain',
        condition_icon: '10d',
        wind_speed: 6.3,
        rain_probability: 80,
      },
      {
        time: 1694691600,
        hour: '17:00',
        temperature: 27,
        humidity: 77,
        condition: 'Light Rain',
        condition_icon: '10d',
        wind_speed: 6.0,
        rain_probability: 75,
      },
      {
        time: 1694695200,
        hour: '18:00',
        temperature: 28,
        humidity: 75,
        condition: 'Cloudy',
        condition_icon: '04d',
        wind_speed: 5.8,
        rain_probability: 40,
      },
      {
        time: 1694698800,
        hour: '19:00',
        temperature: 27,
        humidity: 77,
        condition: 'Cloudy Night',
        condition_icon: '04n',
        wind_speed: 6.1,
        rain_probability: 45,
      },
    ],

    alerts: ['Light rain warning'],
    source: 'YourWeatherDB v1.0',
  },

  'Paris': {
    id: 'city_004',
    name: 'Paris',
    country: 'France',
    region: 'Île-de-France',
    coordinates: {
      latitude: 48.8566,
      longitude: 2.3522,
      altitude: 35,
    },
    timezone: 'Europe/Paris',
    lastUpdated: '2026-09-14T09:28:29Z',

    current_conditions: {
      temperature: 18,
      temperature_feels_like: 16,
      condition: 'Scattered Clouds',
      condition_icon: '03d',
      condition_description: 'Scattered clouds in the sky',
      humidity: 68,
      pressure: 1014,
      pressure_trend: 'stable',
      dew_point: 12,
      visibility: 10000,
      uv_index: 4,
      wind: {
        speed: 3.2,
        direction: 'NE',
        direction_degrees: 45,
        gust: 5.8,
      },
      rain_1h: 0,
      snow_1h: 0,
      cloud_coverage: 40,
    },

    sunrise_sunset: {
      sunrise: 1694706000,
      sunset: 1694749200,
      day_length: 43200,
    },

    hourly_forecast: [
      {
        time: 1694706000,
        hour: '12:00',
        temperature: 18,
        humidity: 68,
        condition: 'Partly Cloudy',
        condition_icon: '03d',
        wind_speed: 3.2,
        rain_probability: 5,
      },
      {
        time: 1694709600,
        hour: '13:00',
        temperature: 19,
        humidity: 66,
        condition: 'Partly Cloudy',
        condition_icon: '03d',
        wind_speed: 3.0,
        rain_probability: 3,
      },
      {
        time: 1694713200,
        hour: '14:00',
        temperature: 20,
        humidity: 64,
        condition: 'Sunny',
        condition_icon: '02d',
        wind_speed: 2.8,
        rain_probability: 0,
      },
      {
        time: 1694716800,
        hour: '15:00',
        temperature: 21,
        humidity: 62,
        condition: 'Sunny',
        condition_icon: '01d',
        wind_speed: 2.6,
        rain_probability: 0,
      },
      {
        time: 1694720400,
        hour: '16:00',
        temperature: 20,
        humidity: 63,
        condition: 'Partly Cloudy',
        condition_icon: '02d',
        wind_speed: 2.8,
        rain_probability: 2,
      },
      {
        time: 1694724000,
        hour: '17:00',
        temperature: 19,
        humidity: 65,
        condition: 'Partly Cloudy',
        condition_icon: '03d',
        wind_speed: 3.0,
        rain_probability: 5,
      },
      {
        time: 1694727600,
        hour: '18:00',
        temperature: 18,
        humidity: 67,
        condition: 'Partly Cloudy Night',
        condition_icon: '03n',
        wind_speed: 3.1,
        rain_probability: 8,
      },
      {
        time: 1694731200,
        hour: '19:00',
        temperature: 17,
        humidity: 69,
        condition: 'Cloudy Night',
        condition_icon: '04n',
        wind_speed: 3.2,
        rain_probability: 10,
      },
    ],

    alerts: [],
    source: 'YourWeatherDB v1.0',
  },

  'Sydney': {
    id: 'city_005',
    name: 'Sydney',
    country: 'Australia',
    region: 'New South Wales',
    coordinates: {
      latitude: -33.8688,
      longitude: 151.2093,
      altitude: 58,
    },
    timezone: 'Australia/Sydney',
    lastUpdated: '2026-09-14T09:28:29Z',

    current_conditions: {
      temperature: 25,
      temperature_feels_like: 24,
      condition: 'Clear Sky',
      condition_icon: '01d',
      condition_description: 'Perfect clear weather',
      humidity: 55,
      pressure: 1018,
      pressure_trend: 'rising',
      dew_point: 15,
      visibility: 10000,
      uv_index: 7,
      wind: {
        speed: 8.5,
        direction: 'SE',
        direction_degrees: 135,
        gust: 12.3,
      },
      rain_1h: 0,
      snow_1h: 0,
      cloud_coverage: 10,
    },

    sunrise_sunset: {
      sunrise: 1694642400,
      sunset: 1694688000,
      day_length: 45600,
    },

    hourly_forecast: [
      {
        time: 1694642400,
        hour: '12:00',
        temperature: 25,
        humidity: 55,
        condition: 'Sunny',
        condition_icon: '01d',
        wind_speed: 8.5,
        rain_probability: 0,
      },
      {
        time: 1694646000,
        hour: '13:00',
        temperature: 26,
        humidity: 53,
        condition: 'Sunny',
        condition_icon: '01d',
        wind_speed: 8.2,
        rain_probability: 0,
      },
      {
        time: 1694649600,
        hour: '14:00',
        temperature: 27,
        humidity: 51,
        condition: 'Sunny',
        condition_icon: '01d',
        wind_speed: 7.8,
        rain_probability: 0,
      },
      {
        time: 1694653200,
        hour: '15:00',
        temperature: 28,
        humidity: 50,
        condition: 'Sunny',
        condition_icon: '02d',
        wind_speed: 7.5,
        rain_probability: 0,
      },
      {
        time: 1694656800,
        hour: '16:00',
        temperature: 27,
        humidity: 51,
        condition: 'Partly Cloudy',
        condition_icon: '02d',
        wind_speed: 7.8,
        rain_probability: 2,
      },
      {
        time: 1694660400,
        hour: '17:00',
        temperature: 26,
        humidity: 52,
        condition: 'Partly Cloudy',
        condition_icon: '02d',
        wind_speed: 8.0,
        rain_probability: 3,
      },
      {
        time: 1694664000,
        hour: '18:00',
        temperature: 25,
        humidity: 54,
        condition: 'Clear Night',
        condition_icon: '01n',
        wind_speed: 8.3,
        rain_probability: 1,
      },
      {
        time: 1694667600,
        hour: '19:00',
        temperature: 24,
        humidity: 56,
        condition: 'Clear Night',
        condition_icon: '01n',
        wind_speed: 8.5,
        rain_probability: 1,
      },
    ],

    alerts: [],
    source: 'YourWeatherDB v1.0',
  },

  'Dubai': {
    id: 'city_006',
    name: 'Dubai',
    country: 'United Arab Emirates',
    region: 'Dubai',
    coordinates: {
      latitude: 25.2048,
      longitude: 55.2708,
      altitude: 5,
    },
    timezone: 'Asia/Dubai',
    lastUpdated: '2026-09-14T09:28:29Z',

    current_conditions: {
      temperature: 38,
      temperature_feels_like: 42,
      condition: 'Clear Sky',
      condition_icon: '01d',
      condition_description: 'Very hot and sunny',
      humidity: 35,
      pressure: 1008,
      pressure_trend: 'stable',
      dew_point: 20,
      visibility: 8000,
      uv_index: 10,
      wind: {
        speed: 12.5,
        direction: 'NW',
        direction_degrees: 315,
        gust: 18.5,
      },
      rain_1h: 0,
      snow_1h: 0,
      cloud_coverage: 2,
    },

    sunrise_sunset: {
      sunrise: 1694659200,
      sunset: 1694702400,
      day_length: 43200,
    },

    hourly_forecast: [
      {
        time: 1694659200,
        hour: '12:00',
        temperature: 38,
        humidity: 35,
        condition: 'Sunny',
        condition_icon: '01d',
        wind_speed: 12.5,
        rain_probability: 0,
      },
      {
        time: 1694662800,
        hour: '13:00',
        temperature: 39,
        humidity: 33,
        condition: 'Sunny',
        condition_icon: '01d',
        wind_speed: 12.2,
        rain_probability: 0,
      },
      {
        time: 1694666400,
        hour: '14:00',
        temperature: 40,
        humidity: 32,
        condition: 'Sunny',
        condition_icon: '01d',
        wind_speed: 11.8,
        rain_probability: 0,
      },
      {
        time: 1694670000,
        hour: '15:00',
        temperature: 41,
        humidity: 31,
        condition: 'Sunny',
        condition_icon: '01d',
        wind_speed: 11.5,
        rain_probability: 0,
      },
      {
        time: 1694673600,
        hour: '16:00',
        temperature: 40,
        humidity: 32,
        condition: 'Partly Cloudy',
        condition_icon: '02d',
        wind_speed: 11.8,
        rain_probability: 0,
      },
      {
        time: 1694677200,
        hour: '17:00',
        temperature: 39,
        humidity: 33,
        condition: 'Partly Cloudy',
        condition_icon: '02d',
        wind_speed: 12.0,
        rain_probability: 0,
      },
      {
        time: 1694680800,
        hour: '18:00',
        temperature: 37,
        humidity: 35,
        condition: 'Clear Night',
        condition_icon: '01n',
        wind_speed: 12.3,
        rain_probability: 0,
      },
      {
        time: 1694684400,
        hour: '19:00',
        temperature: 36,
        humidity: 37,
        condition: 'Clear Night',
        condition_icon: '01n',
        wind_speed: 12.5,
        rain_probability: 0,
      },
    ],

    alerts: ['High heat advisory'],
    source: 'YourWeatherDB v1.0',
  },
};

// Get weather for any city
export const getYourWeather = (cityName) => {
  const city = Object.keys(YOUR_WEATHER_DATABASE).find(
    key => key.toLowerCase() === cityName.toLowerCase()
  );

  if (city) {
    return YOUR_WEATHER_DATABASE[city];
  }

  // Return London as default if city not found
  return YOUR_WEATHER_DATABASE['London'];
};

// Get all available cities
export const getAllYourCities = () => {
  return Object.keys(YOUR_WEATHER_DATABASE);
};

// Get formatted weather summary
export const getWeatherSummary = (cityName) => {
  const weather = getYourWeather(cityName);
  return {
    city: weather.name,
    country: weather.country,
    temperature: weather.current_conditions.temperature,
    condition: weather.current_conditions.condition,
    humidity: weather.current_conditions.humidity,
    wind_speed: weather.current_conditions.wind.speed,
  };
};
